# Generated by Django 3.1.2 on 2020-10-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bqthrooms',
            new_name='bathrooms',
        ),
    ]
